### ISSUE TITLE
Change the UI

### ISSUE THREAD

**Issue by gureks** [gureks/random-password-chrome-extension#4]
It would be great if someone could help build the UI for the extension. Preferably I'm looking for something based on Google's Materialize CSS.

P.S. I'm giving away Digital Ocean stickers to Indians resolving any issue via post.

**Comment by dhwanilvyas** [comment]
I would love to work on it.
Just to be clear which library are you talking about?
[Materialize CSS](http://materializecss.com/) or [Google's Material Design Library](https://getmdl.io/started/index.html)

**Comment by gureks** [comment]
@dhwanilvyas Thanks for taking this up, I'm assigning it to you. 
I would **prefer** Materialize CSS  but go with anything you like. :D 

P.S. I'm giving away Digital Ocean stickers to Indians resolving any issue via post.

**Comment by dhwanilvyas** [comment]
Alright I am on it.
And thanks I am glad to hear that. 😄

**Comment by dhruvdutt** [comment]
I would love to work on this. I believe this is taken already.
Maybe I could help enhancing it in future.

**Comment by gureks** [comment]
@dhruvdutt if @dhwanilvyas drops it, you can take it up. :)

**Comment by owenvoke** [comment]
Looks like it's resolved in #9 (looks good btw)

**Comment by gureks** [comment]
Thanks @dhwanilvyas for the UI. 
@PXgamer Yeah! I merged it. BTW I'll putting it up on Chrom Webstore soon. 😄
