### ISSUE TITLE
Fix the password strength

### ISSUE THREAD

**Issue by gureks** [gureks/random-password-chrome-extension#5]
All the options give almost similar passwords which are hard to remember. I would suggest changes in the array from which the password is created.

**Comment by owenvoke** [comment]
Gunna take a look at this (not asking for it to be assigned).

**Comment by gureks** [comment]
> prestonkyles commented 11 minutes ago
> 
> When trying to generate different strengths of passwords, I find that it's using the same generator. When I want to generate a weak password, which should only be lowercase characters, there are uppercase characters in there. I'm not very experienced with Chrome extensions so I couldn't find the issue in code.

**Comment by owenvoke** [comment]
I'm happy to take this on, I think I may see why 😄

**Comment by owenvoke** [comment]
Let me know if that works for you 😄

**Comment by gureks** [comment]
@PXgamer  Thanks a lot. 
This resolved the issue.
