### ISSUE TITLE
Password Strength Generation Bugged

### ISSUE THREAD

**Issue by ghost** [gureks/random-password-chrome-extension#6]
This might relate to issue #5 

When trying to generate different strengths of passwords, I find that it's using the same generator. When I want to generate a weak password, which should only be lowercase characters, there are uppercase characters in there. I'm not very experienced with Chrome extensions so I couldn't find the issue in code.

**Comment by owenvoke** [comment]
This is exactly what I noticed.

**Comment by gureks** [comment]
This is exactly what I meant in #5 
The issue is somewhere in the main.js or the between the form tags in popup.html but can't get what exactly.

I'm closing this here and copying your point in #5.
